# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13m4Tx_zxOvF0kHIpXPqcUsIo6wm5svrH
"""

import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import yfinance as yf

df = pd.read_csv("/content/sample_data/indexData.csv")

# ============================================================
# HIGH LEVEL QUANT ANALYST PROJECT
# AI STOCK RETURN PREDICTION SYSTEM
# ============================================================

# INSTALL LIBRARIES FIRST
# !pip install yfinance ta xgboost scikit-learn matplotlib

# ============================================================
# IMPORT LIBRARIES
# ============================================================

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from ta.trend import SMAIndicator, MACD
from ta.momentum import RSIIndicator

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

from xgboost import XGBClassifier
!pip install yfinance ta xgboost scikit-learn matplotlib

# ============================================================
# DOWNLOAD STOCK DATA
# ============================================================

ticker = "AAPL"

data = yf.download(
    ticker,
    start="2020-01-01",
    end="2025-01-01"
)

# ============================================================
# FIX CLOSE PRICE DIMENSION ISSUE
# ============================================================

close_prices = data['Close'].iloc[:, 0]

# ============================================================
# FEATURE ENGINEERING
# ============================================================

# DAILY RETURN
data['Return'] = close_prices.pct_change()

# SIMPLE MOVING AVERAGES
data['SMA_10'] = SMAIndicator(
    close=close_prices,
    window=10
).sma_indicator()

data['SMA_50'] = SMAIndicator(
    close=close_prices,
    window=50
).sma_indicator()

# RSI
data['RSI'] = RSIIndicator(
    close=close_prices,
    window=14
).rsi()

# MACD
macd = MACD(close=close_prices)

data['MACD'] = macd.macd()

# VOLATILITY
data['Volatility'] = (
    data['Return']
    .rolling(window=10)
    .std()
)

# ============================================================
# TARGET VARIABLE
# ============================================================

# 1 = STOCK GOES UP
# 0 = STOCK GOES DOWN

data['Target'] = np.where(
    close_prices.shift(-1) > close_prices,
    1,
    0
)

# ============================================================
# CLEAN DATA
# ============================================================

data.dropna(inplace=True)

# ============================================================
# FEATURES & LABELS
# ============================================================

features = [
    'SMA_10',
    'SMA_50',
    'RSI',
    'MACD',
    'Volatility'
]

X = data[features]

y = data['Target']

# ============================================================
# TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    shuffle=False
)

# ============================================================
# MODEL TRAINING
# ============================================================

model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=5,
    random_state=42
)

model.fit(X_train, y_train)

# ============================================================
# PREDICTIONS
# ============================================================

predictions = model.predict(X_test)

# ============================================================
# MODEL EVALUATION
# ============================================================

accuracy = accuracy_score(y_test, predictions)

print("\n==============================")
print("MODEL ACCURACY")
print("==============================")

print(f"Accuracy: {accuracy:.2f}")

print("\n==============================")
print("CLASSIFICATION REPORT")
print("==============================")

print(classification_report(y_test, predictions))

# ============================================================
# STRATEGY RETURNS
# ============================================================

test_data = data.iloc[-len(X_test):].copy()

test_data['Prediction'] = predictions

# STRATEGY RETURN
test_data['Strategy_Return'] = (
    test_data['Return']
    * test_data['Prediction']
)

# MARKET RETURN
test_data['Market_Return'] = (
    1 + test_data['Return']
).cumprod()

# STRATEGY RETURN
test_data['Strategy_Total_Return'] = (
    1 + test_data['Strategy_Return']
).cumprod()

# ============================================================
# SHARPE RATIO
# ============================================================

sharpe_ratio = (
    test_data['Strategy_Return'].mean()
    /
    test_data['Strategy_Return'].std()
) * np.sqrt(252)

print("\n==============================")
print("SHARPE RATIO")
print("==============================")

print(f"Sharpe Ratio: {sharpe_ratio:.2f}")

# ============================================================
# NEXT DAY PREDICTION
# ============================================================

latest_data = X.tail(1)

next_prediction = model.predict(latest_data)[0]

print("\n==============================")
print("NEXT DAY PREDICTION")
print("==============================")

if next_prediction == 1:
    print("STOCK MAY GO UP TOMORROW")
else:
    print("STOCK MAY GO DOWN TOMORROW")

# ============================================================
# VISUALIZATION
# ============================================================

plt.figure(figsize=(14,7))

plt.plot(
    test_data.index,
    test_data['Market_Return'],
    label='Market Return'
)

plt.plot(
    test_data.index,
    test_data['Strategy_Total_Return'],
    label='Strategy Return'
)

plt.title(f'{ticker} AI Quant Trading Strategy')

plt.xlabel('Date')

plt.ylabel('Cumulative Return')

plt.legend()

plt.grid(True)

plt.show()

# ============================================================
# FEATURE IMPORTANCE
# ============================================================

importance = pd.DataFrame({
    'Feature': features,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print("\n==============================")
print("FEATURE IMPORTANCE")
print("==============================")

print(importance)



!pip install yfinance ta xgboost scikit-learn matplotlib

!pip install ta yfinance xgboost

import streamlit as st
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

st.title("AI Stock Return Predictor")

ticker = st.text_input("Enter Stock Symbol", "AAPL")

data = yf.download(ticker, start="2023-01-01")

st.write(data.tail())

# Plot Closing Price
fig, ax = plt.subplots(figsize=(10,5))

ax.plot(data.index, data['Close'])

ax.set_title(f"{ticker} Stock Price")

st.pyplot(fig)

!pip install streamlit

!pip install streamlit yfinance ta xgboost scikit-learn matplotlib pandas numpy

!pip install streamlit pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("Stock Prediction App")
# st.write("Hello World")

!streamlit run app.py &>/content/logs.txt &

from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)

!streamlit run streamlit_app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# 
# import streamlit as st
# 
# st.title("My Streamlit App")
# st.write("App Running Successfully")

!ls

!streamlit run /content/streamlit_app.py

!streamlit run streamlit_app.py
